defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      show_date: true
      read_time: true
      share: false
      related: false
      author_profile: false
      footnotes: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      show_date: true
      footnotes: false

compress_html:
  clippings: all

title: The blog of Adisakshya Chauhan
email: hi@adisakshya.codes
description: >- # this means to ignore newlines until "baseurl:"
  A compilation of Adisakshya's musings ğŸ¤”, inspirations ğŸŒŸ, mistakes ğŸ˜…, and other ramblings ğŸ§.
baseurl: "/weblog"
url: "https://adisakshya.github.io"
twitter_username: adisakshya
github_username:  adisakshya
search: true
repository: adisakshya/weblog

# Build settings
# theme: "minimal-mistakes-jekyll"
remote_theme: "mmistakes/minimal-mistakes@4.22.0"
plugins:
  - jekyll-include-cache
  - jekyll-paginate

comments:
  provider  : "staticman_v2"
  staticman:
    branch    : "master"
    endpoint  : "https://adisakshya-staticman.herokuapp.com/v3/entry/github/"

author:
  name: "Adisakshya Chauhan"
  avatar: "assets/images/avatar.jpg"
  bio: "A student developer who loves learning new things and proactively seek new concepts every day"
  location: "28.6245Â° N, 77.0914Â° E"
  links:
    - label: "Adisakshya Codes"
      icon: "fas fa-fw fa-link"
      url: "https://adisakshya.codes"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/adisakshya"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/adisakshya"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/adisakshya"

footer:
  links:
    - label: "twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/adisakshya"
    - label: "github"
      icon: "fab fa-github"
      url: "https://github.com/adisakshya"
    - label: "website"
      icon: "fab fa-firefox"
      url: "/"
    - label: "linkedin"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/adisakshya/"
    - label: "google"
      icon: "fab fa-google"
      url: "mailto:hi@adisakshya.codes"

include: ["_pages"]
exclude: ["README.md"]

paginate: 5
paginate_path: "/page:num/"
